name: Trigger Cloud Run Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'deploys/Deploy-GitHub-Actions-GCR/**'
  pull_request:
    branches:
      - main
    paths:
      - 'deploys/Deploy-GitHub-Actions-GCR/**'

jobs:
  call-cicd:
    uses: ./deploys/Deploy-GitHub-Actions-GCR/.github/workflows/cicd.yaml
    secrets: inherit