name: Trigger Cloud Run Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'Deploys/Deploy-GitHub-Actions-GCR/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Deploys/Deploy-GitHub-Actions-GCR/**'

jobs:
  call-cicd:
    uses: ./.github/workflows/deploy-gcr-reusable.yaml
    secrets: inherit